# mkdocs.yml
site_name: "Speedrunning League Badges"
theme:
  name: material
  font:
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: octicons/moon-24
        name: Switch to light mode


nav:
    - Home: index.md

    - API Reference:
        - api_reference/credits.md
        - api_reference/leaderboard.md

plugins:
  - search
  - privacy
  - mkdocstrings

watch:
  - docs
  - README.md
  - src

