name: Auto Releases

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-conventional-releases

    - name: Run python-conventional-releases
      run: python -m conventional_release

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: release-branch
        title: 'New Release'
        body: 'This is an automated PR for a new release'
        base: main
